"""empty message

Revision ID: 86b9a90ca632
Revises: 
Create Date: 2021-05-03 10:50:21.334579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86b9a90ca632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timekeeping_schedule')
    op.drop_index('log_schedule_idx', table_name='log')
    op.drop_index('log_user_idx', table_name='log')
    op.drop_table('log')
    op.drop_table('conversation')
    op.drop_index('salary_emp_idx', table_name='salary')
    op.drop_table('salary')
    op.alter_column('employee', 'mail',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50),
               nullable=True)
    op.alter_column('employee', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50),
               nullable=True)
    op.alter_column('employee', 'salary',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('index1', table_name='employee')
    op.drop_column('employee', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=70), nullable=False))
    op.create_index('index1', 'employee', ['id'], unique=False)
    op.alter_column('employee', 'salary',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('employee', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50),
               nullable=False)
    op.alter_column('employee', 'mail',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50),
               nullable=False)
    op.create_table('salary',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), server_default=sa.text("'9999-01-01'"), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], name='salary_emp'),
    sa.PrimaryKeyConstraint('id', 'emp_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('salary_emp_idx', 'salary', ['emp_id'], unique=False)
    op.create_table('conversation',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mess_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=500), nullable=True),
    sa.Column('time_create', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['employee.id'], name='chat_user'),
    sa.PrimaryKeyConstraint('user_id', 'mess_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('log',
    sa.Column('emp_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time_in', mysql.TIME(), nullable=True),
    sa.Column('time_out', mysql.TIME(), nullable=True),
    sa.Column('tag_in', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_out', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_log_in', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image_log_out', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_correct_face_in', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_correct_face_out', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], name='log_user'),
    sa.ForeignKeyConstraint(['schedule_id'], ['timekeeping_schedule.id'], name='log_schedule'),
    sa.PrimaryKeyConstraint('date', 'schedule_id', 'emp_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('log_user_idx', 'log', ['emp_id'], unique=False)
    op.create_index('log_schedule_idx', 'log', ['schedule_id'], unique=False)
    op.create_table('timekeeping_schedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), server_default=sa.text("'9999-01-01'"), nullable=True),
    sa.Column('start_time_in', mysql.TIME(), nullable=True),
    sa.Column('end_time_in', mysql.TIME(), nullable=True),
    sa.Column('correct_time_in', mysql.TIME(), nullable=True),
    sa.Column('start_time_out', mysql.TIME(), nullable=True),
    sa.Column('end_time_out', mysql.TIME(), nullable=True),
    sa.Column('correct_time_out', mysql.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
